name: Project Portability Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: portability-check-${{ github.ref }}
  cancel-in-progress: true

  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties
        
      - name: Clean and Build
      #Ensuring project doesnt only work on our devices
        run: |
          chmod +x gradlew
          ./gradlew clean assembleDebug --stacktrace
